//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proekt_TRPO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        public int Id { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string НомерСтуденческого { get; set; }
        public Nullable<int> IdГруппы { get; set; }
    
        public virtual Группы Группы { get; set; }
    }
}
